package controller.api.staff;


import com.google.gson.Gson;
import model.Staff;
import util.Database;
import util.Utils;

import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.sql.*;

@Path("staff")
@Produces(MediaType.APPLICATION_JSON)
public class StaffResource {

    @GET
    public String getStaff() throws SQLException {

        String query = "SELECT * FROM account, employee WHERE account.id = employee.account_id";

        try (Connection conn = Database.getConnection();
             PreparedStatement st = conn.prepareStatement(query)) {

            ResultSet rs = st.executeQuery();
            return new Gson().toJson(Database.toList(rs));
        }
    }

    @POST
    public Response addStaff(String postData) throws SQLException {
       try (Connection conn = Database.getConnection();
        PreparedStatement st = conn.prepareStatement(
                "INSERT INTO account (username, userhash, role) VALUES ((?), (?), (?))",
                Statement.RETURN_GENERATED_KEYS)) {

            Gson gson = new Gson();

            Staff staff = gson.fromJson(postData, Staff.class);

            if (staff.isValid()) {
                st.setString(1, staff.username);
                st.setString(2, staff.userhash);
                st.setInt(3, staff.role);
                st.executeUpdate();

                // get the ID that was generated by auto increment
                ResultSet rs = st.getGeneratedKeys();
                rs.next();
                staff.id = rs.getInt(1);

                return Response.ok(Utils.toJson(staff)).build();
            } else {
                return Response.status(Response.Status.BAD_REQUEST).build();
            }
        }
    }
}
